/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ligamxadmin;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JComponent;
import javax.swing.plaf.basic.BasicMenuBarUI;

/**
 *
 * @author mshvc2
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    
    private String nombre = "Liga Mx";
    private Color backgroundColor = new Color(235, 235, 235);
    private Color menuBarColor = new Color(25, 20, 74);
    public GUI() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBar = new javax.swing.JPanel();
        jLabelIconBar = new javax.swing.JLabel();
        jLabelInfoBar = new javax.swing.JLabel();
        jPanelList = new javax.swing.JPanel();
        jPanelMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(235, 235, 235));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanelBar.setBackground(new java.awt.Color(25, 20, 74));
        jPanelBar.setPreferredSize(new java.awt.Dimension(800, 48));
        jPanelBar.setLayout(null);

        jLabelIconBar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelIconBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ligamx/Icons/home2.png"))); // NOI18N
        jLabelIconBar.setPreferredSize(new java.awt.Dimension(48, 48));
        jPanelBar.add(jLabelIconBar);
        jLabelIconBar.setBounds(8, 0, 48, 48);

        jLabelInfoBar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelInfoBar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfoBar.setText("Menu Principal");
        jLabelInfoBar.setPreferredSize(new java.awt.Dimension(144, 48));
        jPanelBar.add(jLabelInfoBar);
        jLabelInfoBar.setBounds(56, 0, 144, 48);

        getContentPane().add(jPanelBar);
        jPanelBar.setBounds(0, 0, 800, 48);

        jPanelList.setBackground(new java.awt.Color(255, 255, 255));
        jPanelList.setPreferredSize(new java.awt.Dimension(192, 536));

        javax.swing.GroupLayout jPanelListLayout = new javax.swing.GroupLayout(jPanelList);
        jPanelList.setLayout(jPanelListLayout);
        jPanelListLayout.setHorizontalGroup(
            jPanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );
        jPanelListLayout.setVerticalGroup(
            jPanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelList);
        jPanelList.setBounds(8, 56, 192, 536);

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMain.setPreferredSize(new java.awt.Dimension(584, 536));

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelMain);
        jPanelMain.setBounds(208, 56, 584, 536);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited

    }//GEN-LAST:event_formMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelIconBar;
    private javax.swing.JLabel jLabelInfoBar;
    private javax.swing.JPanel jPanelBar;
    private javax.swing.JPanel jPanelList;
    private javax.swing.JPanel jPanelMain;
    // End of variables declaration//GEN-END:variables
}
